In [17]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('heart_disease.csv')

In [44]:
data.Gender.unique()

array([1, 0])

In [3]:
data

,Gender,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Heart_ stroke
0,Male,39,postgraduate,0,0.0,0.0,no,0,0,195.0,106.0,70.0,26.97,80.0,77.0,No
1,Female,46,primaryschool,0,0.0,0.0,no,0,0,250.0,121.0,81.0,28.73,95.0,76.0,No
2,Male,48,uneducated,1,20.0,0.0,no,0,0,245.0,127.5,80.0,25.34,75.0,70.0,No
3,Female,61,graduate,1,30.0,0.0,no,1,0,225.0,150.0,95.0,28.58,65.0,103.0,yes
4,Female,46,graduate,1,23.0,0.0,no,0,0,285.0,130.0,84.0,23.10,85.0,85.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,Male,50,uneducated,1,1.0,0.0,no,1,0,313.0,179.0,92.0,25.97,66.0,86.0,yes
4234,Male,51,graduate,1,43.0,0.0,no,0,0,207.0,126.5,80.0,19.71,65.0,68.0,No
4235,Female,48,primaryschool,1,20.0,NaN,no,0,0,248.0,131.0,72.0,22.00,84.0,86.0,No
4236,Female,44,uneducated,1,15.0,0.0,no,0,0,210.0,126.5,87.0,19.16,86.0,NaN,No
4237,Female,52,primaryschool,0,0.0,0.0,no,0,0,269.0,133.5,83.0,21.47,80.0,107.0,No

In [4]:
data.drop(columns=['education'],inplace=True)

In [5]:
data.dropna(inplace=True)

In [6]:
data

,Gender,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Heart_ stroke
0,Male,39,0,0.0,0.0,no,0,0,195.0,106.0,70.0,26.97,80.0,77.0,No
1,Female,46,0,0.0,0.0,no,0,0,250.0,121.0,81.0,28.73,95.0,76.0,No
2,Male,48,1,20.0,0.0,no,0,0,245.0,127.5,80.0,25.34,75.0,70.0,No
3,Female,61,1,30.0,0.0,no,1,0,225.0,150.0,95.0,28.58,65.0,103.0,yes
4,Female,46,1,23.0,0.0,no,0,0,285.0,130.0,84.0,23.10,85.0,85.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4231,Male,58,0,0.0,0.0,no,1,0,187.0,141.0,81.0,24.96,80.0,81.0,No
4232,Male,68,0,0.0,0.0,no,1,0,176.0,168.0,97.0,23.14,60.0,79.0,yes
4233,Male,50,1,1.0,0.0,no,1,0,313.0,179.0,92.0,25.97,66.0,86.0,yes
4234,Male,51,1,43.0,0.0,no,0,0,207.0,126.5,80.0,19.71,65.0,68.0,No
4237,Female,52,0,0.0,0.0,no,0,0,269.0,133.5,83.0,21.47,80.0,107.0,No

In [7]:
data['Gender'] = data['Gender'].replace(['Male','Female'],[1,0])

C:\Users\rituh\AppData\Local\Temp\ipykernel_13044\899162920.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Gender'] = data['Gender'].replace(['Male','Female'],[1,0])

In [8]:
data

,Gender,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Heart_ stroke
0,1,39,0,0.0,0.0,no,0,0,195.0,106.0,70.0,26.97,80.0,77.0,No
1,0,46,0,0.0,0.0,no,0,0,250.0,121.0,81.0,28.73,95.0,76.0,No
2,1,48,1,20.0,0.0,no,0,0,245.0,127.5,80.0,25.34,75.0,70.0,No
3,0,61,1,30.0,0.0,no,1,0,225.0,150.0,95.0,28.58,65.0,103.0,yes
4,0,46,1,23.0,0.0,no,0,0,285.0,130.0,84.0,23.10,85.0,85.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4231,1,58,0,0.0,0.0,no,1,0,187.0,141.0,81.0,24.96,80.0,81.0,No
4232,1,68,0,0.0,0.0,no,1,0,176.0,168.0,97.0,23.14,60.0,79.0,yes
4233,1,50,1,1.0,0.0,no,1,0,313.0,179.0,92.0,25.97,66.0,86.0,yes
4234,1,51,1,43.0,0.0,no,0,0,207.0,126.5,80.0,19.71,65.0,68.0,No
4237,0,52,0,0.0,0.0,no,0,0,269.0,133.5,83.0,21.47,80.0,107.0,No

In [9]:
data.prevalentStroke.unique()

array(['no', 'yes'], dtype=object)

In [10]:
data['prevalentStroke'] = data['prevalentStroke'].replace(['yes','no'],[1,0])

C:\Users\rituh\AppData\Local\Temp\ipykernel_13044\1543184241.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['prevalentStroke'] = data['prevalentStroke'].replace(['yes','no'],[1,0])

In [11]:
data

,Gender,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Heart_ stroke
0,1,39,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,No
1,0,46,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,No
2,1,48,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,No
3,0,61,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,yes
4,0,46,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4231,1,58,0,0.0,0.0,0,1,0,187.0,141.0,81.0,24.96,80.0,81.0,No
4232,1,68,0,0.0,0.0,0,1,0,176.0,168.0,97.0,23.14,60.0,79.0,yes
4233,1,50,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,yes
4234,1,51,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,No
4237,0,52,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,No

In [12]:
data['Heart_ stroke'].unique()

array(['No', 'yes'], dtype=object)

In [13]:
data['Heart_ stroke'] = data['Heart_ stroke'].replace(['No','yes'],[0,1])

C:\Users\rituh\AppData\Local\Temp\ipykernel_13044\751353614.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Heart_ stroke'] = data['Heart_ stroke'].replace(['No','yes'],[0,1])

In [14]:
data

,Gender,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Heart_ stroke
0,1,39,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4231,1,58,0,0.0,0.0,0,1,0,187.0,141.0,81.0,24.96,80.0,81.0,0
4232,1,68,0,0.0,0.0,0,1,0,176.0,168.0,97.0,23.14,60.0,79.0,1
4233,1,50,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4237,0,52,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [23]:
data_input = data.drop(columns=['Heart_ stroke'])
data_output = data['Heart_ stroke']

In [24]:
data_output.value_counts()

Heart_ stroke
0    3177
1     572
Name: count, dtype: int64

In [26]:
from imblearn.over_sampling import SMOTE

In [27]:
sm = SMOTE(random_state=2)

In [31]:
data_input,data_output = sm.fit_resample(data_input,data_output.ravel())

In [32]:
np.unique(data_output, return_counts=True)

(array([0, 1]), array([3177, 3177]))

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
x_train , x_test , y_train , y_test = train_test_split(data_input, data_output,test_size=0.2)

In [36]:
model = LogisticRegression()

In [37]:
model.fit(x_train, y_train)

c:\Users\rituh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [38]:
model.score(x_test, y_test)

0.6475216365066876

In [39]:
input = np.array([[0,59,0,0,0,0,1,0,209,150,85,20.77,90,88]])

In [40]:
x = model.predict(input)

c:\Users\rituh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [41]:
x[0]

np.int64(1)

In [42]:
import pickle as pk

In [43]:
pk.dump(model , open('Heart_disease_model.pkl','wb'))

In [45]:
data_input

,Gender,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose
0,1,39,0,0.0,0.0,0,0,0,195.000000,106.000000,70.000000,26.970000,80.000000,77.000000
1,0,46,0,0.0,0.0,0,0,0,250.000000,121.000000,81.000000,28.730000,95.000000,76.000000
2,1,48,1,20.0,0.0,0,0,0,245.000000,127.500000,80.000000,25.340000,75.000000,70.000000
3,0,61,1,30.0,0.0,0,1,0,225.000000,150.000000,95.000000,28.580000,65.000000,103.000000
4,0,46,1,23.0,0.0,0,0,0,285.000000,130.000000,84.000000,23.100000,85.000000,85.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6349,0,64,0,0.0,0.0,0,0,0,273.588425,123.196142,72.813504,22.949229,75.196142,82.234725
6350,0,53,0,0.0,0.0,0,1,1,237.590858,151.472254,85.219808,28.725301,66.535365,260.085967
6351,0,59,0,0.0,0.0,0,0,0,272.043733,133.260933,83.391400,25.533098,91.304667,61.565600
6352,1,62,1,43.0,0.0,0,0,0,217.000000,109.632667,69.028531,22.610057,73.175464,67.706134
6353,1,59,1,20.0,0.0,0,0,0,260.000000,127.365670,72.485074,25.112836,65.000000,74.701490